package com.example.final_project.model.enums;

public enum TrainerName {
    NICK_MITCHELL, MATT_ROBERTS, LOUISE_PARKER, SHAUN_STAFFORD, SCOTT_LAIDLER, EMMA_CHAN, NICOLE_STANFORD,
    SHANON_MICHAEL, JOHN_SIEMENS, SANDRA_SIMONS, JESSICA_PORTERS, MICHAEL_SMITH, SIMON_SAIGON, DARA_MIKO,
    GAMET_GARADJ, JACKIE_WARNER, ALEXIA_CLARK, JOE_DOWDELL, KAYLA_ITSINES, CHRISTIAN_THIBAUDEAU
}
