spring:
    datasource:
        password:
        url: jdbc:mysql://localhost:3306/mobilelelele?createDatabaseIfNotExist=true&useSSL=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: true
        show-sql: true
