package com.example.final_project.model.enums;

public enum Clubs {
    LAS_TORTUGA, LONDON_PEARL, PARIS_DIAMOND, CASE_DE_SANTORINI,
    VIVA_DE_FLORANCE, MALAGA_PEARL, ALICANTE_DIAMOND, MADRID_MILLENNIAL, MILANO_MILLENNIAL, CASE_VENEZIA,
    WEST_MALLING, ROYSTON_DIAMOND, LONDON_MILLENNIAL, COLOMBES, HOUILLES, AMIENS_MILLENNIAL, MANASTIRSKI_LIVADI,
    MLADOST, DELUXE, RING_MALL, GRAFENWOHR, RAMSTEIN, WIESBADEN, BERLIN_PEARL, UTRECHT, OOSTZAAN, EINDHOVEN,
    AMSTERDAM
}
