package com.example.final_project.model.enums;

public enum Title {
    FITNESS_MANIACS, OPTIMIZED_TRAINING, INSTRUCTIVELY, ACTIVATE_ACADEMY, INNER_GROWTH, TIMELY_TRAINING,
    GRADE_POTENTIAL, THE_WATCHERS, COURSE_METHOD, CORPORATE_BUILDERS, COSMIC_BRAIN, NANO_TRAINER,
    FLEX_ED, FOCUS_FITNESS, LESSON_UP
}
